# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('eventoPrincipal', models.CharField(max_length=200, verbose_name='eventoPrincipal')),
                ('sigla', models.CharField(max_length=10, verbose_name='sigla')),
                ('dataEhoraDeInicio', models.DateTimeField(verbose_name='dataEhoraDeInicio')),
                ('palavrasChave', models.CharField(max_length=50, verbose_name='palavrasChave')),
                ('logoTipo', models.CharField(max_length=50, verbose_name='logoTipo')),
                ('cidade', models.CharField(max_length=50, verbose_name='cidade')),
                ('uf', models.CharField(max_length=5, verbose_name='uf')),
                ('endereco', models.CharField(max_length=200, verbose_name='endereco')),
                ('cep', models.CharField(max_length=50, verbose_name='cep')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='g1.Pessoa')),
                ('curriculo', models.TextField(verbose_name='curriculo')),
            ],
            bases=('g1.pessoa', models.Model),
        ),
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='g1.Evento')),
                ('issn', models.CharField(max_length=200, verbose_name='issn')),
            ],
            bases=('g1.evento', models.Model),
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='g1.Pessoa')),
                ('cpf', models.CharField(max_length=50, verbose_name='cpf')),
            ],
            bases=('g1.pessoa', models.Model),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='g1.Pessoa')),
                ('cnpj', models.CharField(max_length=50, verbose_name='cnpj')),
                ('razaoSocial', models.CharField(max_length=100, verbose_name='razaoSocial')),
            ],
            bases=('g1.pessoa', models.Model),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='g1.PessoaFisica')),
                ('dataHoraInscricao', models.DateTimeField(verbose_name='data')),
                ('tipoInscricao', models.CharField(max_length=50, verbose_name='tipoInscricao')),
            ],
            bases=('g1.pessoafisica', models.Model),
        ),
    ]
